name = "SBMLFBCModels"
uuid = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
authors = ["The authors of SBMLFBCModels.jl"]
version = "1.1.0"

[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AbstractFBCModels = "1"
DocStringExtensions = "0.8, 0.9"
SBML = "1.5"
SparseArrays = "1"
Test = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
