name = "SBMLFBCModels"
uuid = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
authors = ["Mirek Kratochvil <miroslav.kratochvil@uni.lu>"]
version = "0.1.0"

[deps]
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"
