name = "SBMLFBCModels"
uuid = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
authors = ["Mirek Kratochvil <miroslav.kratochvil@uni.lu>"]
version = "0.1.0"

[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"

[compat]
DocStringExtensions = "0.9"
julia = "1"
